### ISSUE TITLE
Driver doesn't support generic slave capabilities reporting

### ISSUE THREAD

**Issue by ruisebastiao** [RobertCNelson/bb-kernel#12]
Hello Robert,

I'm using linux kernel version 4.0 + yocto to boot my Beaglebone, i'm getting the follwing error:

8.635924] ------------[ cut here ]------------
[    8.666477] WARNING: CPU: 0 PID: 141 at /home/automacao/poky/build-bbb/tmp/work-
shared/beaglebone/kernel-source/drivers/dma/dmaengine.c:863 
dma_async_device_register+0x2c4/0x4dc()
[    8.904406] this driver doesn't support generic slave capabilities reporting
[    9.003185] Modules linked in: ti_am335x_adc kfifo_buf musb_am335x(+) industrialio 
sch_fq_codel
[    9.076880] CPU: 0 PID: 141 Comm: systemd-udevd Not tainted 4.0.0-rc7-beagleboard.org #1
[    9.085561] Hardware name: Generic AM33XX (Flattened Device Tree)
[    9.092000] Backtrace: 
[    9.094610] c00139c0] (dump_backtrace) from c0013be4>] (show_stack+0x18/0x1c)
[    9.102588]  r6:c0bf0720 r5:c0bf0720 r4:00000000 r3:dc8ba200
[    9.108576] c0013bcc>] (show_stack) from c07d9ee8>] (dump_stack+0x8c/0xcc)
[    9.116200] c07d9e5c>] (dump_stack) from c00433bc>] (warn_slowpath_common+0x90/0xc0)
[    9.124720]  r6:c04a50f8 r5:00000009 r4:dc8e79d0 r3:dc8ba200
[    9.130724] c004332c>] (warn_slowpath_common) from c0043424>]
(warn_slowpath_fmt+0x38/0x40)
[    9.139850]  r8:000000b2 r7:dc8e5000 r6:dc892410 r5:00000000 r4:c0a7ce4c
[    9.146961] c00433f0>] (warn_slowpath_fmt) from c04a50f8>] 
(dma_async_device_register+0x2c4/0x4dc)
[    9.156773]  r3:00000000 r2:c0a7ce4c
[    9.160569]  r4:dc892410
[    9.163244] c04a4e34>] (dma_async_device_register) from c04a9b8c>] 
(cppi41_dma_probe+0x430/0x480)
[    9.172946]  r10:c144c450 r9:c084cc50 r8:000000b2 r7:dc8e5000 r6:dc8e5010 r5:00000000
[    9.181229]  r4:dc892410
[    9.183905] c04a975c>] (cppi41_dma_probe) from c05273b0>] 
(platform_drv_probe+0x4c/0xac)
[    9.192795]  r10:0000000e r9:c14a9d74 r8:c0bf3844 r7:fffffdfb r6:c0bf3844 r5:dc8e5010
[    9.201081]  r4:c14a9db8
[    9.203753] c0527364>] (platform_drv_probe) from c05253a4>] 
(driver_probe_device+0x144/0x3a4)
[    9.213089]  r7:00000000 r6:c0c39df8 r5:dc8e5010 r4:c14a9db8
[    9.219064] c0525260>] (driver_probe_device) from c052564c>] (__device_attach+0x48/0x4c)
[    9.227944]  r10:00000000 r9:c14a9d74 r8:00000000 r7:dc8e5010 r6:c0525604 r5:dc8e5010
[    9.236227]  r4:c0bf3844
[    9.238906] c0525604>] (__device_attach) from c052355c>] (bus_for_each_drv+0x6c/0xa0)
[    9.247515]  r5:dc8e5010 r4:00000000
[    9.251316] c05234f0>] (bus_for_each_drv) from c05251f0>] (device_attach+0x80/0x94)
[    9.259715]  r6:dc8e5044 r5:dc8e5010 r4:dc8e5010
[    9.264617] c0525170>] (device_attach) from c05246d0>] (bus_probe_device+0x90/0xb4)
[    9.273042]  r6:c0bfd8f0 r5:dc8e5010 r4:dc8e5018 r3:dd887e00
[    9.279019] c0524640>] (bus_probe_device) from c0522670>] (device_add+0x3f0/0x58c)
[    9.287354]  r6:c0b9ee08 r5:dd9d0410 r4:dc8e5018 r3:00000003
[    9.293366] c0522280>] (device_add) from c0695bb0>] (of_device_add+0x3c/0x44)
[    9.301247]  r10:dd9d0410 r9:c0c410b8 r8:dfaa78f8 r7:00000000 r6:ffffffff r5:dc8e5010
[    9.309502]  r4:dc8e5000
[    9.312201] c0695b74>] (of_device_add) from c06964b0>] 
(of_platform_device_create_pdata+0x12c/0x210)
[    9.322184] c0696384>] (of_platform_device_create_pdata) from c06966b4>] 
(of_platform_bus_create+0x104/0x21c)
[    9.332979]  r9:00000000 r8:00000000 r7:00000001 r6:00000000 r5:dfaa78ac r4:00000000
[    9.341178] c06965b0>] (of_platform_bus_create) from c0696958>] 
(of_platform_populate+0x64/0xb4)
[    9.350787]  r10:0000000a r9:00000001 r8:dd9d0410 r7:00000000 r6:00000000 r5:dfaa6690
[    9.359044]  r4:dfaa78ac
[    9.361755] c06968f4>] (of_platform_populate) from bf01b030>] 
(am335x_child_probe+0x30/0x4c [musb_am335x])
[    9.372279]  r9:dc950d40 r8:bf01b220 r7:fffffdfb r6:bf01b220 r5:dd9d0400 r4:dd9d0410
[    9.380455] bf01b000>] (am335x_child_probe [musb_am335x]) from c05273b0>] 
(platform_drv_probe+0x4c/0xac)
[    9.390800]  r5:dd9d0410 r4:c14a9db8
[    9.394573] c0527364>] (platform_drv_probe) from c05253a4>] 
(driver_probe_device+0x144/0x3a4)
[    9.403911]  r7:00000000 r6:c0c39df8 r5:dd9d0410 r4:c14a9db8
[    9.409885] c0525260>] (driver_probe_device) from c05256ec>] (__driver_attach+0x9c/0xa0)
[    9.418763]  r10:c0b9ee08 r9:dc950d40 r8:c0ba2920 r7:00000000 r6:dd9d0444 r5:bf01b220
[    9.427045]  r4:dd9d0410
[    9.429714] c0525650>] (__driver_attach) from c0523498>] (bus_for_each_dev+0x74/0xa8)
[    9.438320]  r6:c0525650 r5:bf01b220 r4:00000000 r3:dd9b509c
[    9.444321] c0523424>] (bus_for_each_dev) from c0524d8c>] (driver_attach+0x24/0x28)
[    9.452744]  r6:c0bfd8f0 r5:dc819ac0 r4:bf01b220
[    9.457615] c0524d68>] (driver_attach) from c05249b0>] (bus_add_driver+0x168/0x224)
[    9.466047] c0524848>] (bus_add_driver) from c0526158>] (driver_register+0x80/0x100)
[    9.474563]  r7:00000000 r6:bf01d000 r5:c0ba2920 r4:bf01b220
[    9.480567] c05260d8>] (driver_register) from c05272f4>] 
(__platform_driver_register+0x5c/0x64)
[    9.490060]  r5:c0ba2920 r4:bf01b264
[    9.493863] c0527298>] (__platform_driver_register) from bf01d020>] 
(am335x_child_init+0x20/0x24 [musb_am335x])
[    9.504857] bf01d000>] (am335x_child_init [musb_am335x]) from c0008af4>] 
(do_one_initcall+0xe0/0x220)
[    9.514934] c0008a14>] (do_one_initcall) from c07d6d30>] (do_init_module+0x68/0x1b8)
[    9.523450]  r10:bf01b264 r9:dc99d808 r8:23662828 r7:00000001 r6:dc950dc0 r5:c0c31e34
[    9.531734]  r4:bf01b264
[    9.534408] c07d6cc8>] (do_init_module) from c00cb0a4>] (load_module+0x1bc4/0x2240)
[    9.542832]  r6:dc99d800 r5:c0c31e34 r4:dc8e7f48
[    9.547706] c00c94e0>] (load_module) from c00cb8d4>] (SyS_finit_module+0x88/0xb8)
[    9.555950]  r10:00000000 r9:dc8e6000 r8:c000fb64 r7:0000017b r6:b6eb2f88 r5:00000008
[    9.564235]  r4:00000000
[    9.566905] c00cb84c>] (SyS_finit_module) from c000f9a0>] (ret_fast_syscall+0x0/0x4c)
[    9.575513]  r6:00000000 r5:b6fa10d0 r4:00000000
[   12.461817] ---[ end trace 26b8e053d9bcbd81 ]---

Here is the full dmesg info:

http://pastebin.com/s6Q1T3sr

maybe here is not the correct place to put the issue, where do i have to report this failure?

Thanks!

**Comment by RobertCNelson** [comment]
Can you share your .config, i haven't personally seen that, looks like something in teh dma setup..
Regards,

**Comment by ruisebastiao** [comment]
My kernel config:

http://pastebin.com/mSiCUXHm

**Comment by ruisebastiao** [comment]
Hi,

after i googled a lit more I saw that the problem was solved with this patch:

http://www.spinics.net/lists/linux-usb/msg122433.html

Thanks for your attention anyway
