### ISSUE TITLE
Cannot create debian packages with build_deb.sh / rebuild_deb.sh

### ISSUE THREAD

**Issue by ghost** [RobertCNelson/bb-kernel#16]
Scripts build_deb.sh or rebuild_deb.sh fails while creating packages:
**debian/changelog(l2): found eof where expected first heading**
That is probably caused by "n/a" at the position of distribution of debian/changelog

_part of the script output_
http://pastebin.com/MuW40R8d

_debian/changelog_
http://pastebin.com/pJsGwhkM

**Comment by RobertCNelson** [comment]
So the make deb-pkg calls: 

```
# Try to determine distribution
if [ -n "$KDEB_CHANGELOG_DIST" ]; then
        distribution=$KDEB_CHANGELOG_DIST
elif distribution=$(lsb_release -cs 2>/dev/null) && [ -n "$distribution" ]; then
        : # nothing to do in this case
else
        distribution="unstable"
        echo >&2 "Using default distribution of 'unstable' in the changelog"
        echo >&2 "Install lsb-release or set \$KDEB_CHANGELOG_DIST explicitly"
fi
```

The "n/a" comes from lsb_release -cs

This is a problem for a few dist's as we've found here:
https://github.com/RobertCNelson/stable-kernel/blob/master/tools/host_det.sh#L148

I'm thinking we should just use the deb_distro value already discovered in host_det.sh as pass as "KDEB_CHANGELOG_DIST"...

Regards,

**Comment by RobertCNelson** [comment]
Please replace your rebuild_deb.sh with this file:
https://raw.githubusercontent.com/RobertCNelson/stable-kernel/master/tools/rebuild_deb.sh
and see if really fixes it. (it should)
Regards,

**Comment by ghost** [comment]
Script now exits succesfully, with few warnings as you can see in:
http://pastebin.com/0czQtwXk

Thank you for your time!
