### ISSUE TITLE
linux-headers-3.8.13-bone74.deb host-architecture binaries

### ISSUE THREAD

**Issue by ghost** [RobertCNelson/bb-kernel#17]
After successfully resolving the issue #16 , and installing deployed package linux-headers-3.8.13-bone74.deb. I attempted to compile some of my kernel modules and got following error:
http://pastebin.com/uHU5YgPt

I figured out that all binaries in kernel headers' package are built for host architecture (x86-64 in my case). If I understand well,  **kernel/scripts** are utilities used during kernel build procedure by host system, so to transfer them to target system they need to be rebuilt with cross toolchain, which does not happen in **build_deb.sh** or **rebuild_deb.sh**

**Comment by RobertCNelson** [comment]
This has always been an issue, haven't found a good way to force the arch to the header creation scripts.

**Comment by ghost** [comment]
Well then, thank you!
