### ISSUE TITLE
Why always download gcc-linaro-arm-linux-gnueabihf-?

### ISSUE THREAD

**Issue by jiapei100** [RobertCNelson/bb-kernel#2]
Hi, Robert:

Whenever I tried to ./build_kernel.sh, I got

https://releases.linaro.org/14.06/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.9-2014.06_linux.tar.xz

I think I can use my own toolchain installed from Ubuntu repository to finish the entire compilation. I mean, without linaro's gcc toolchain, I should also be able to compile the kernel.

So, if I insist on using my own toolchain, is there such an option in ./build_kernel.sh?

Cheers
Pei

**Comment by RobertCNelson** [comment]
Right here: (system.sh.sample -> system.sh)
https://github.com/RobertCNelson/bb-kernel/blob/am33x-v3.8/system.sh.sample#L15

**Comment by jiapei100** [comment]
Hi, Robert:

## It seems this is not the case. As you can see, my CC has already been set to "/usr/bin/arm-linux-gnueabihf-", the process "Installing: gcc-linaro-arm-linux-gnueabihf

--2014-08-02 13:25:40--  https://releases.linaro.org/14.06/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.9-2014.06_linux.tar.xz" goes on...

➜  BBB  cd bb-kernel 
➜  bb-kernel git:(master) git checkout origin/am33x-v3.16 -b tmp
Branch tmp set up to track remote branch am33x-v3.16 from origin.
Switched to a new branch 'tmp'
➜  bb-kernel git:(tmp) ./build_kernel.sh 
- Detected build host [Ubuntu 14.04.1 LTS]
- host: [x86_64]
- git HEAD commit: [b8ebf9232b229a4f2600dcc003f07b0a7dbf0bef]
  ‘/home/pei/Downloads/Boards/BBB/bb-kernel/system.sh.sample’ -> ‘/home/pei/Downloads/Boards/BBB/bb-kernel/system.sh’
  
  ## Installing: gcc-linaro-arm-linux-gnueabihf
  
  --2014-08-02 13:25:40--  https://releases.linaro.org/14.06/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.9-2014.06_linux.tar.xz
  Resolving releases.linaro.org (releases.linaro.org)... 54.83.198.186
  Connecting to releases.linaro.org (releases.linaro.org)|54.83.198.186|:443... connected.
  HTTP request sent, awaiting response... 200 OK
  Length: 50602320 (48M) [application/force-download]
  Saving to: ‘/home/pei/Downloads/Boards/BBB/bb-kernel/dl/gcc-linaro-arm-linux-gnueabihf-4.9-2014.06_linux.tar.xz’
  
  2% [                                       ] 1,253,376    161KB/s  eta 5m 53s ^C
  ➜  bb-kernel git:(tmp) echo $CC
  /usr/bin/arm-linux-gnueabihf-
  ➜  bb-kernel git:(tmp) 

So, any further suggestions/solutions?

Cheers
Pei

**Comment by RobertCNelson** [comment]
What's the output of:

```
cat system.sh | grep CC
```

Otherwise i haven't bothered to setup the script to read the environment variable CC.

Regards,

**Comment by jiapei100** [comment]
Hi, Robert:

Thank you for your prompt reply. You are right.
I've got to set "CC" by modifying system.sh, instead of exporting an environmental variable.

Cheers
