### ISSUE TITLE
Serial device /dev/ttyS1 not working in Kernel 4.1.17-bone-rt-r18 

### ISSUE THREAD

**Issue by QuickJack** [RobertCNelson/bb-kernel#22]
Device names have changed from /dev/ttyO\* to /dev/ttyS*. I have loaded the overlay for UART1 using uEnv.txt by adding cape_enable=bone_capemgr.enable_partno=BB-UART1

The driver seems to get loaded according to

dmesg|grep ttyS1
[    3.722985] 48022000.serial: ttyS1 at MMIO 0x48022000 (irq = 155, base_baud = 3000000) is a 8250

No data is output on the TXD1 line. The same test works perfectly using Kernel 3.8.13 and /dev/ttyO1.

**Comment by RobertCNelson** [comment]
Sorry I fixed this in r19..

https://github.com/RobertCNelson/bb-kernel/commits/am33x-rt-v4.1

Only change..
