### ISSUE TITLE
Nothing under pkgconfig

### ISSUE THREAD

**Issue by jiapei100** [RobertCNelson/bb-kernel#3]
Hi, Robert:

I followed your manual http://eewiki.net/display/linuxonarm/BeagleBone+Black
and have Ubuntu14.04 successfully installed. However, I noticed there is nothing under
/usr/lib/pkgconfig
/usr/lib/arm-linux-gnueabihf/pkgconfig
/usr/local/pkgconfig (this is reasonable)

It looks the default installation of Ubuntu 14.04 doesn't have those .pc files under pkgconfig folders. Sometimes when I tried to install my own packages, those packages are actually searching for some particular .pc files. Did you meet this issue before?

Cheers
Pei

**Comment by RobertCNelson** [comment]
Did you install pkg-config?
http://packages.ubuntu.com/search?searchon=contents&keywords=pc&mode=&suite=trusty&arch=any

For ubuntu bugs:
https://launchpad.net/

**Comment by jiapei100** [comment]
So, Robert:

Do you mean ubuntu-14.04-minimal-armhf-2014-07-07.tar.xz is buggy but maintained by launchpad, instead of you??
wget -c https://rcn-ee.net/deb/minfs/trusty/ubuntu-14.04-minimal-armhf-2014-07-07.tar.xz

Again, after 
sudo tar xfvp ./_-_-_-armhf-_/armhf-rootfs-*.tar -C /media/rootfs/ 
there is nothing in /usr/lib/pkgconfig and /usr/lib/arm-linux-gnueabihf/pkgconfig .

And, I had pkg-config installed after the system successfully booted. pkg-config is not defautly installed. I'm sure pkg-config is not in ubuntu-14.04-minimal-armhf-2014-07-07.tar.xz   ...

Cheers
Pei

**Comment by RobertCNelson** [comment]
Hi Pei,

No what i mean, "ubuntu-14.04-minimal-armhf-2014-07-07.tar.xz" is generated directly from  ports.ubuntu.com so if you find a bug in one of the packages, it's best to report it to launchpad. I "only" provide the kernel. (the kernel/scripts is for this bug "issues" area)

pkg-config is not installed by default.

I'm certain if you install something like: 

```
sudo apt-get update
sudo apt-get install libcrypto++-dev pkg-config
```

You'll find: /usr/lib/pkgconfig/libcrypto++.pc
