### ISSUE TITLE
HDMI port not showing kernel boot log

### ISSUE THREAD

**Issue by JamesHagerman** [RobertCNelson/bb-kernel#33]
I finally sat down and walked through the instructions here:

[https://eewiki.net/display/linuxonarm/BeagleBone+Black#BeagleBoneBlack-LinuxKernel](https://eewiki.net/display/linuxonarm/BeagleBone+Black#BeagleBoneBlack-LinuxKernel) 

in an attempt to get a working BBB image.

I'm using the Ubuntu root fs and am33x-v4.4, entirely fresh and it looks like it's hanging because three status LEDs come on and then just stay lit. 

Is there a way to get the boot long to actually show up on the screen? I'll get the serial interface out this weekend if not...

Thanks!
James

**Comment by RobertCNelson** [comment]
@JamesHagerman 3-led is a sign you skipped over this section:

https://eewiki.net/display/linuxonarm/BeagleBone+Black#BeagleBoneBlack-DealingwitholdBootloaderineMMC

Regards,

**Comment by JamesHagerman** [comment]
Ah! Right! I got that figured now.

Is there a trick to getting the actual kernel boot to display on the BBB's hdmi port though? (I don't mean u-boot...)

Thanks for the help!
