### ISSUE TITLE
What is the meaning for device-tree-compiler ?

### ISSUE THREAD

**Issue by jiapei100** [RobertCNelson/bb-kernel#4]
Hi, Nelson:

Just wondering what is the purpose for "device-tree-compiler" ? The following patch in your manual

Upgrade distro "device-tree-compiler" package
~/
wget -c https://raw.github.com/RobertCNelson/tools/master/pkgs/dtc.sh
chmod +x dtc.sh
./dtc.sh

I noticed that this patch of code install something on my local laptop as the installation mentioned:
     LD fdtput
     LD libfdt/libfdt-1.4.0.so
Installing into: /usr/local/bin/
[sudo] password for pei: 
    CHK version_gen.h
     INSTALL

➜  BBB  ls /usr/local/lib/libfdt*
/usr/local/lib/libfdt-1.4.0.so  /usr/local/lib/libfdt.so
/usr/local/lib/libfdt.a         /usr/local/lib/libfdt.so.1

But, will this dtc influence the future installation on the Beaglebone Black?? I doubt... 
So, what is this "device-tree-compiler" for?

Cheers
Pei

**Comment by RobertCNelson** [comment]
```
Device Tree Compiler (dtc) - converts between the human editable device
tree source "dts" format and the compact device tree blob "dtb"
representation usable by the kernel.
```

http://elinux.org/Device_Tree

All general questions should be posted here:
https://groups.google.com/forum/#!forum/beagleboard

This issue tracker is NOT a forum.
