### ISSUE TITLE
Cannot build modules on installed 4.4.59 kernel

### ISSUE THREAD

**Issue by altr0n** [RobertCNelson/bb-kernel#43]
I have built and installed the following kernel version on my BBB:

Linux beaglebone 4.4.59-bone17 #1 Thu Apr 6 13:05:33 EDT 2017 armv7l GNU/Linux

I get errors when I attempt to run the following Makefile to build a patched gadgetfs driver:.

```
ccflags-y := -I$(srctree)/drivers/usb/gadget/
ccflags-y += -I$(srctree)/drivers/usb/gadget/udc/
ccflags-y += -I$(srctree)/drivers/usb/gadget/function/
obj-m+=gadgetfs.o
gadgetfs-objs=inode.o
codepath=/lib/modules/$(shell uname -r)/build/
aux=
modules:
	make $(aux) -C $(codepath) M=$(PWD) modules
clean:
	make $(aux) -C $(codepath) M=$(PWD) clean
```

The errors are as follows:

```
debian@beaglebone:~/test/umap2/gadget$ sudo make modules
make  -C /lib/modules/4.4.59-bone17/build/ M= modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.59-bone17'
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[2]: *** No rule to make target 'arch/arm/tools/gen-mach-types', needed by 'include/generated/mach-types.h'.  Stop.
arch/arm/Makefile:313: recipe for target 'archprepare' failed
make[1]: *** [archprepare] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.59-bone17'
Makefile:19: recipe for target 'modules' failed
make: *** [modules] Error 2
```

I am almost certain that this is likely a problem with how I installed the resulting .deb files that were output from the `build_deb.sh` script but I have not been able to find any solutions that allow me to compile these modules properly.

**Comment by RobertCNelson** [comment]
While cross-compiling the *.deb files has it uses.  The cross-built linux-headers*.deb has always been hit and miss

Please re-check with the native deb packages:
```
sudo apt update
sudo apt install linux-image-4.4.59-bone17 linux-headers-4.4.59-bone17
```

Regards,

**Comment by altr0n** [comment]
Ok, after doing that and rebooting I am still getting the following error:

```
debian@beaglebone:~/test/umap2/gadget$ sudo make modules
make  -C /lib/modules/4.4.59-bone17/build/ M= modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.59-bone17'
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  UPD     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
make[2]: *** No rule to make target 'arch/arm/tools/gen-mach-types', needed by 'include/generated/mach-types.h'.  Stop.
arch/arm/Makefile:313: recipe for target 'archprepare' failed
make[1]: *** [archprepare] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.59-bone17'
Makefile:19: recipe for target 'modules' failed
make: *** [modules] Error 2
```

I was told my someone else to attempt to run ```sudo make modules_prepare``` from the ```/usr/src/linux-headers-4.4.59-bone17/``` directory, but running that also gives the following error:

```
debian@beaglebone:/usr/src/linux-headers-4.4.59-bone17$ sudo make modules_prepare
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[1]: *** No rule to make target 'arch/arm/tools/gen-mach-types', needed by 'include/generated/mach-types.h'.  Stop.
arch/arm/Makefile:313: recipe for target 'archprepare' failed
make: *** [archprepare] Error 2
```

**Comment by RobertCNelson** [comment]
I think since your including these directories:
```
ccflags-y := -I$(srctree)/drivers/usb/gadget/
ccflags-y += -I$(srctree)/drivers/usb/gadget/udc/
ccflags-y += -I$(srctree)/drivers/usb/gadget/function/
```
it's trying to build all those dependicy's too. so a full kernel build..

since we give you the source, wouldn't be easier to just add your module under drivers/usb/gadget ?

Regards,

**Comment by altr0n** [comment]
Turns out to be something completely different and this issue was not needed.

In order to build the module properly I just needed to be the root user. I am really sorry for wasting your time on this!

Thanks so much for your time!

**Comment by RobertCNelson** [comment]
Crazy!  wonder if fakeroot would work too..

**Comment by mmisagh** [comment]
> In order to build the module properly I just needed to be the root user. I am really sorry for wasting your time on this!

Thanks @altr0n  , that worked for me,too.
