### ISSUE TITLE
running against linux-next

### ISSUE THREAD

**Issue by HarelAshwal** [RobertCNelson/bb-kernel#46]
LK"I

Is it possible to run the automated script against linux-next repository?

Thanks,
Harel

**Comment by RobertCNelson** [comment]
@HarelAshwal i do have a repo here:

https://github.com/RobertCNelson/linux-next

i use it mostly, when i push things mainline..

recently i setup a jenkins instance on linode, would it be useful to do daily snapshots (*.deb files)

http://rcn-ee.online:8080/

Regards,

**Comment by HarelAshwal** [comment]
LK"I

I See , Great,
How often this repo is being updated? once a mounth ?

Harel

**Comment by HarelAshwal** [comment]
LK"I

Another thing, is it also apply all BB patches?

youre scripts/web sites are extremly usefull :) 

Thanks,
Harel

**Comment by RobertCNelson** [comment]
That's my linux-dev repo.

**Comment by HarelAshwal** [comment]
LK"I

So that means it doesn't include the patches?
Can I apply those patches to that repository?
I need the latest linux... (there is some new driver I need to use...)
Harel

**Comment by RobertCNelson** [comment]
Use the linux-dev repo then

**Comment by HarelAshwal** [comment]
I tried linux-dev repo, it clonse the latest mainline linux, it didn't pull the linux-next repo.

**Comment by RobertCNelson** [comment]
@HarelAshwal not sure what you want..

I have "my" linux-next:

https://github.com/RobertCNelson/linux-next

Which I use when "I" need..

adn i have my linux-dev:

https://github.com/RobertCNelson/linux-dev

Which is my development feeder into my stable branches..

If "you" need something more, 'we' can gladly talk about a $ contract..

Otherwise, my free time is mostly spoken for already.

Regards,

**Comment by HarelAshwal** [comment]
LK"I

Okay, 
Just asking if there is any repo that includes the linux-next & the patches.

**Comment by RobertCNelson** [comment]
@HarelAshwal rebasing a patchset takes a lot of work and dedication when dealing with linux-next.

**Comment by HarelAshwal** [comment]
LK"I

I See,
Thanks for all your great support!

You're doing a wonderfull work !!!
Harel
