### ISSUE TITLE
Upstreaming to Buildroot

### ISSUE THREAD

**Issue by bbros-dev** [RobertCNelson/bb-kernel#58]
Is there a technical or functional reason your BB related kernels, uboot, rootfs, packages etc haven't been up-streamed into [BuildRoot](https://buildroot.org) a machine/board?
Specifically, I am wondering if I was to try to create a BuildRoot machine def if I should expect to hit headaches?

It appears that buildroot could save me some hassle, but I've yet to use it in anger.

On a closer look it seemed to me that [Yocto](https://yoctoproject.org) is overkill for a BB build.

**Comment by RobertCNelson** [comment]
Long Story @bbros-dev , but when I originally started working on Debian for the BeagleBoard "Family" about 10 years ago, there was many Buildroot and Yocto Developers maintaining those sub-projects for Buildroot and Yocto... But no one for Debian...

So my personal Goal was to get Debian to the same level as Buildroot/Yocto.. ;)

So now, 10 years later... Opps..

Regards,

**Comment by bbros-dev** [comment]
Thanks again for all the work you've put in.  You're right: now your repo's are alive a well and there is no BeagleBone in buildroot.

Would it help you to have a buildroot config? If so I could likely help with some of the initial work.

At the moment I'm building something for my son to use, so not sure how long I'll have my hands in this space, and I'm cautious about leaving something behind that is effectively an additional maintenance burden.

It might lessen newbie questions like mine, but I'm not familiar enough with this user space to know where the pain points typically are.

**Comment by RobertCNelson** [comment]
There is this one:

https://github.com/buildroot/buildroot/blob/master/configs/beaglebone_defconfig

**Comment by bbros-dev** [comment]
I was sure I looked ;)
