### ISSUE TITLE
kernel 5.4 exFAT backport patch missing CONFIG rename

### ISSUE THREAD

**Issue by mr-russ** [RobertCNelson/bb-kernel#63]
Using the 5.4 branch for the kernel from Repo.

The patch file ```bb-kernel/patches/backports/exfat/0001-backports-exfat-from-linux.git.patch``` renames most instances of CONFIG_EXFAT_FS to CONFIG_STAGING_EXFAT_FS, however it missing one, and even with the variables set it does not appear in /proc/filesystems when built.  It does appear in /proc/config.gz so I know that it's configured to be included.

After applying the folliwng change to the output
```
root@kernel-build:~/bb-kernel/KERNEL# git diff
diff --git a/drivers/staging/Makefile b/drivers/staging/Makefile
index a90f9b308c8d..a1354a941df0 100644
--- a/drivers/staging/Makefile
+++ b/drivers/staging/Makefile
@@ -51,5 +51,5 @@ obj-$(CONFIG_KPC2000)         += kpc2000/
 obj-$(CONFIG_ISDN_CAPI)                += isdn/
 obj-$(CONFIG_UWB)              += uwb/
 obj-$(CONFIG_USB_WUSB)         += wusbcore/
-obj-$(CONFIG_EXFAT_FS)         += exfat/
+obj-$(CONFIG_STAGING_EXFAT_FS) += exfat/
 obj-$(CONFIG_QLGE)             += qlge/
```

After building with that change, the filesystem is available in ```/proc/filesystems```

**Comment by RobertCNelson** [comment]
Thanks @mr-russ ! i'll merge that in.

**Comment by RobertCNelson** [comment]
Fixed with: https://github.com/RobertCNelson/bb-kernel/commit/7907cb594625d68bdcc94fdd86b6e8bc1a45ac39
