### ISSUE TITLE
Patch for CPSW breaks if PM is disabled

### ISSUE THREAD

**Issue by sophec** [RobertCNelson/bb-kernel#66]
While building kernel 5.10 without CONFIG_PM, it was failing in the DaVinci MDIO driver, which I found odd. It turns out that [this patch](https://github.com/RobertCNelson/bb-kernel/blob/am33x-rt-v5.10/patches/drivers/ti/cpsw/0001-cpsw-search-for-phy.patch) defines the function `davinci_mdio_update_dt_from_phymask` inside of a block checking if `CONFIG_PM` is enabled, which seems unrelated to the functionality of this patch. I have since patched it to move that function to just after that block and the kernel built successfully. I have attached the patch if it is of any use, though I doubt you'll need my patch for this. I just added this to the patches/drivers/ti/cpsw directory and it built fine. I'm not sure this issue will affect nearly anyone, as the *vast* majority of people will have CONFIG_PM enabled, but in any case this was an issue and this patch fixes it.

(Note: I had to add .txt for GitHub to allow me to upload the file, but of course it is a valid git patch.)
Edit: updated the patch
[0002-cpsw-fix-undefined-function-with-PM-disabled.patch.txt](https://github.com/RobertCNelson/bb-kernel/files/6533824/0002-cpsw-fix-undefined-function-with-PM-disabled.patch.txt)

**Comment by sophec** [comment]
Aaaaand I just realized vim decided to format when I moved the function, so I'll have to fix that. However, the patch will work the same.

**Comment by sophec** [comment]
I have updated the patch now so that it is readable.

**Comment by RobertCNelson** [comment]
Thanks @willeccles added this to our tree, it'll start hitting every branch. ;)

**Comment by sophec** [comment]
Thanks! I'll close this issue now.
